### ISSUE TITLE
WebService sample: an error in C# source code and empty Result panel

### ISSUE THREAD

**Issue by DaniilVeriga** [deckdotnet/Deck.NET#27] opened 2018-06-07 10:26 UTC
https://deck.net/webservice

Chrome

![webservice](https://user-images.githubusercontent.com/1510884/41094310-8366a49e-6a56-11e8-81a0-a2ea9e1db122.png)

**Comment by geoffreymcgill** [comment] 2018-06-07 19:42
Hi @DaniilVeriga Thanks for this report. This compiler error was triggered by the last release of Retyped and has been fixed. With some luck, we will be releasing a big new update to Retyped this coming weekend, and this exception will automatically pick up the fix.

I'll close this issue once the sample is confirmed to be working again.

**Comment by fabriciomurta** [comment] 2018-06-11 05:55
The aspect displayed in the report is fixed with the updated Retyped packages. But now it fails because it does not want to return `null`, but just `void`.

**Comment by geoffreymcgill** [comment] 2018-06-11 12:31
The Deck sample is now working correctly.

**Closed by geoffreymcgill** 2018-06-11 12:31 UTC
